interface AppConfigInterface {
  ownerRoles: string[];
  customerRoles: string[];
  tenantRoles: string[];
  tenantName: string;
  applicationName: string;
  addOns: string[];
  ownerAbilities: string[];
  customerAbilities: string[];
}
export const appConfig: AppConfigInterface = {
  ownerRoles: ['Owner'],
  customerRoles: [],
  tenantRoles: ['Owner', 'Accountant'],
  tenantName: 'Client',
  applicationName: 'Billing Application for my small company',
  addOns: ['file upload', 'chat', 'notifications', 'file'],
  customerAbilities: [],
  ownerAbilities: [
    "Manage Client's information",
    'Invite Accountant to the application',
    'View payment history recorded by Accountant',
    "Delete Client's payment history",
    'View invoices generated by Accountant',
  ],
};
